{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "", "test_name": "test_verify_outputXML", "test_id": "TC01", "test_desc": "Validating Output XML file", "rerun": "0"}, "1": {"status": "FAIL", "message": "AssertionError: FAILURE: \u001b[31mcheck 0 == 41: Not Zero<br>test_validateAnthemXmlXl.py:44 in test_verify_commonReport() -> check.equal(0, v, msg=\"Not Zero\")<br>\u001b[0m<br>------------------------------------------------------------<br>Failed Checks: 1<br>------------------------------------------------------------<br>self = <test_validateAnthemXmlXl.TestAnthem object at 0x00000150E5A7BFA0><br><br>    def test_verify_commonReport(self):<br>        \"\"\"TC02 Validating Common report data against input XML data\"\"\"<br>        CommReportCheck = commonReportCheck('SAM_ARTIFACTS/input_xml/31KT_Plan.xml',<br>                                            'SAM_ARTIFACTS/common_report/duplicate_nodes_common_report.xlsx')<br>    <br>        output = CommReportCheck.validateXmlData()<br>        column_mismatch_dict = output[0]<br>        output_file = output[1]<br>        flag = False<br>        failed_list = []<br>        for k, v in column_mismatch_dict.items():<br>            # print(k, v)<br>            # assert column_mismatch_dict[k] == 0, f\"for column {k}, the mismatch count is {column_mismatch_dict[k]}\"<br>            check.equal(0, v, msg=\"Not Zero\")<br>            if column_mismatch_dict[k] != 0:<br>                print(f\"for column {k}, the mismatch count is {column_mismatch_dict[k]}\")<br>                flag = True<br>                failed_list.append(k)<br>        if flag:<br>            failed_columns = \" \".join(item for item in failed_list)<br>>           raise AssertionError(f\"\\nIn Columns {failed_columns} there were mismatches when the Excel report \"<br>                                 f\"was compared with the XML Data.\\n Please refer to the \"<br>                                 f\"file located at {output_file} for more details\")<br>       AssertionError: <br>       In Columns SIT_TYPE_VAL there were mismatches when the Excel report was compared with the XML Data.<br>        Please refer to the file located at output_files/xml_vs_xl.xlsx for more details<br><br>test_validateAnthemXmlXl.py:51: AssertionError<br>", "test_name": "test_verify_commonReport", "test_id": "TC02", "test_desc": "Validating Common report data against input XML data", "rerun": "0"}, "2": {"status": "FAIL", "message": "", "test_name": "test_verify_sibing_duplicates", "test_id": "TC03", "test_desc": "Validating the Sibling duplicates in the common report against the input XML data", "rerun": "0"}}, "suite_name": "test_validateAnthemXmlXl.py"}}}, "date": "December 09, 2022", "start_time": 1670566828.4759207, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}